### ISSUE TITLE
Making this run in a Visual Studio project

### ISSUE THREAD

**Issue by CraigAP** [jwasil/angular-esri-playground#2]
I, along with many other developers, use Visual Studio as my primary development tool.  It would be so valuable to have a starter Visual Studio project that can be the basis for building apps that use the latest from ESRI and Angular.  I've tried to create a Visual Studio 2015 project based on the code in this repository.  It can be found at [https://github.com/CraigAP/Angular2MapStart.git].  It builds, but trying to run it results in JavaScript errors.

**Comment by jwasilgeo** [comment]
Hi @CraigAP, I'm glad to hear you are trying this out and I appreciate the feedback.  I should mention that this repository isn't guaranteed to be completely up-to-date, and is intended to be an example of what could be possible for developers using Esri JSAPI 3.x and Angular 1.x.

Have you been able to try out some of the concepts in the primary "flagship" repo [angular-esri-map v1](https://arcgis.github.io/angular-esri-map-site-v1/)?  For a more specific and stripped down example, can you re-create the JavaScript errors you encounter using the angular-esri-map v1 [readme quickstart](https://github.com/Esri/angular-esri-map/tree/v1.x#quick-start)?

I recommend you try that out, and feel free to then move this issue over to that repo.

**Comment by jwasilgeo** [comment]
@CraigAP since you opened this issue now over in https://github.com/jwasilgeo/angular2-esri-playground/issues/6, I'll go ahead and close this.
